# https://docs.helix-editor.com/configuration.html
theme = "onedark"

[editor]
# line-number = "relative"
# auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-w = ":q" # quit (overrides default of window mode)